movieProject/movies/forms.py
from flask_wtf import FlaskForm
from wtforms import TextAreaField, IntegerField, SubmitField
from wtforms.validators import DataRequired, NumberRange

class AddRating(FlaskForm):
    score = IntegerField('Score: ', validators=[
        DataRequired(message='Please enter a score. (1-5)'),
        NumberRange(min=1, max=5, message='Score must be between 1 and 5')
    ])
    review = TextAreaField('Review: ')
    submit = SubmitField('Submit Review')

movieProject/movies/views.py
from flask import Blueprint, render_template, redirect, request, url_for
from model import Movie, Rating, db
from movies.forms import AddRating
from flask_login import current_user


movies_blueprint = Blueprint('movies', __name__, template_folder='templates/movies')

@movies_blueprint.route('/all_movies')
def all_movies():

    movies = Movie.query.all()

    return render_template('all_movies.html', movies=movies)


@movies_blueprint.route('/movie_details/<movie_id>', methods=["GET", "POST"])
def movie_details(movie_id):
    movie =  Movie.query.filter_by(id=movie_id).first()

    form = AddRating()

    if request.method == "POST":
        if form.validate_on_submit():
            user = current_user

            movieRating = Rating(
                score=form.score.data,
                movie_id=movie.id,
                user_id=user.id,
                review=form.review.data
            )

            db.session.add(movieRating)
            db.session.commit()

            return redirect(url_for('ratings.my_ratings'))

    return render_template('movie_details.html', movie=movie, form=form)

movieProject/movies/templates/movies/all_movies.html
{% extends 'base.html' %}

{% block content %}
    <div class="jumbotron container-fluid row flex" >
        <h1>Movie Gallery</h1>
        <p>Click the movie to view details and Rate</p>
        <div class="row">
            {% for movie in movies %}
                <div class="col-md-2 mb-4">
                    <a href="{{ url_for('movies.movie_details', movie_id=movie.id) }}">        
                        <img src="{{ movie.poster_path }}" alt="{{ movie.title }}" class="rounded galleryImg img-thumbnail" >
                    </a>
                    <br>
                    {{ movie.title }} - {{ movie.release_date.strftime('%Y-%m-%d') }}
                </div>
                {% endfor %}
        </div>
    </div>
{% endblock %}

movieProject/movies/templates/movies/movie_details.html
{% extends 'base.html' %}

{% block content %}
    <div class="jumbotron container-fluid row flex">
        {% if movie %}
        <div class="row">
            <div class="col-md-5">
                <img class="img-thumbnail" src="{{ movie.poster_path }}" alt="{{ movie.title }}" style="width: 100%;">
            </div>
            <div class="col-md-5">
                <h4>
                    Title: {{ movie.title }} <br>
                </h4>
                    Summary: {{ movie.overview }} <br>
                    Release Date: {{ movie.release_date }} <br>
                <div class="col-md-6">
                    <form action="{{ url_for('movies.movie_details', movie_id=movie.id) }}" method="post">
                        {{ form.hidden_tag() }}
                        <ul class="list-group">
                            <li class="list-group-item">
                                {{ form.score.label }} {{ form.score() }}
                            </li>
                            <li class="list-group-item">
                                {{ form.review.label }} {{ form.review() }}
                            </li>
                            <li class="list-group-item">
                                {{ form.submit() }}
                            </li>
                        </ul>
                    </form>
                </div>
            </div>
        </div>
        {% endif %}
    </div>
{% endblock %}