movieProject/movies/forms.py
from flask_wtf import FlaskForm
from wtforms import TextAreaField, IntegerField, SubmitField
from wtforms.validators import DataRequired, NumberRange

class AddRating(FlaskForm):
    score = IntegerField('Score: ', validators=[
        DataRequired(message='Please enter a score. (1-5)'),
        NumberRange(min=1, max=5, message='Score must be between 1 and 5')
    ])
    review = TextAreaField('Review: ')
    submit = SubmitField('Submit Review')

movieProject/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, ValidationError
from wtforms.validators import DataRequired, EqualTo, Email
from model import User


class LoginForm(FlaskForm):
    email = StringField('email: ', validators=[DataRequired(), Email()])
    password = PasswordField('Password: ', validators=[DataRequired()])
    submit = SubmitField('Log in')

class RegistrationForm(FlaskForm):
    email = StringField('email: ', validators=[DataRequired(), Email()])
    password = PasswordField('Password: ', validators=[DataRequired(),EqualTo('pass_confirm', message='Passwords must match!')])
    pass_confirm = PasswordField('Confirm Password: ', validators=[DataRequired()])
    submit = SubmitField('Register!')


    def check_email(self, field):
        if User.query.filter_by(email=field.data).first():
            raise ValidationError('Email already taken. Try again')

movieProject/movies/views.py
from flask import Blueprint, render_template, redirect, request, url_for
from model import Movie, Rating, db
from movies.forms import AddRating
from flask_login import current_user


movies_blueprint = Blueprint('movies', __name__, template_folder='templates/movies')

@movies_blueprint.route('/all_movies')
def all_movies():

    movies = Movie.query.all()

    return render_template('all_movies.html', movies=movies)


@movies_blueprint.route('/movie_details/<movie_id>', methods=["GET", "POST"])
def movie_details(movie_id):
    movie =  Movie.query.filter_by(id=movie_id).first()

    form = AddRating()

    if request.method == "POST":
        if form.validate_on_submit():
            user = current_user

            movieRating = Rating(
                score=form.score.data,
                movie_id=movie.id,
                user_id=user.id,
                review=form.review.data
            )

            db.session.add(movieRating)
            db.session.commit()

            return redirect(url_for('ratings.my_ratings'))

    return render_template('movie_details.html', movie=movie, form=form)

movieProject/ratings/views.py
from flask import Blueprint, render_template, redirect, request, url_for
from model import Movie, Rating, db
from movies.forms import AddRating
from flask_login import current_user


ratings_blueprint = Blueprint('ratings', __name__, template_folder='templates/ratings')

@ratings_blueprint.route('/my_ratings')
def my_ratings():

    user = int(current_user.id)
    print(f'user id print {user}')

    rating_data = []
    ratings = Rating.query.filter_by(user_id = user).all()
    for rating in ratings:
        movie = Movie.query.filter_by(id = rating.movie_id).first()
        rating.poster_path = movie.poster_path
        rating_data.append({
            "movie_id": movie.id
            ,"rating": rating.score
            ,"year": movie.release_date
            , "title": movie.title
            , "overview": movie.overview
            , "poster_path": movie.poster_path
            , "review": rating.review
            })
 
    return render_template('my_ratings.html', rating_data=rating_data)

movieProject/users/views.py
from flask import Blueprint, render_template, redirect, request, url_for, flash , session
from flask_login import login_user, login_required, logout_user
from flask_bcrypt import Bcrypt
from users.forms import LoginForm,RegistrationForm
from model import User, get_by_email, db

bcrypt = Bcrypt()

users_blueprint = Blueprint('users', __name__, template_folder='templates/users')

@users_blueprint.route('/welcome')
@login_required
def welcome_user():
    return render_template('welcome_user.html')


@users_blueprint.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You logged out!')
    return redirect(url_for('home'))



@users_blueprint.route('/login', methods=['GET','POST'])
def login():

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        print(user)
        if user is not None and user.check_password(form.password.data):
            login_user(user)
            flash('Logged in Successfully!')

            next = request.args.get('next')

            if next == None or not next[0] == '/':
                next = url_for('users.welcome_user')

            return redirect(next)
        
    return render_template('login.html', form=form)
    
@users_blueprint.route('/register', methods = ['GET', 'POST'])
def register():
    form = RegistrationForm()

    if form.validate_on_submit():

        user = User(email = form.email.data,
                    password = form.password.data)
        
        db.session.add(user)
        db.session.commit()
        print(user.json())
        flash('Thanks for registration!')
        return redirect(url_for('users.login'))
    
    return render_template('register.html', form=form)

movieProject/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>{% block title %}{% endblock %}</title>
    {% block head %}{% endblock %}
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='styles.css') }}"
    />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
      crossorigin="anonymous"
    />
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
      integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
      integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
      crossorigin="anonymous"
    ></script>
  </head>
  <body>
    <nav class="navbar navbar-dark bg-dark navbar-expand-lg">
      <div class="container-fluid">
        <ul class="navbar-nav mr-auto">
          <a class="navbar-brand" href="#">Movie Rate</a>
          <li class="nav-item">
            <a class="nav-item nav-link" href="{{url_for('home')}}">Home</a>
          </li>
          {% if current_user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-item nav-link" href="{{url_for('movies.all_movies')}}"
              >All Movies</a
            >
          </li>
          <li class="nav-item">
            <a
              class="nav-item nav-link"
              href="{{url_for('ratings.my_ratings')}}"
              >My Reviews</a
            >
          </li>
          <li class="nav-item">
            <a class="nav-item nav-link" href="{{url_for('users.logout')}}"
              >Logout</a
            >
          </li>
          {% else %}

          <li class="nav-item">
            <a class="nav-item nav-link" href="{{url_for('users.login')}}"
              >Log In</a
            >
          </li>
          <li class="nav-item">
            <a class="nav-item nav-link" href="{{url_for('users.register')}}"
              >Register</a
            >
          </li>
          {% endif %}
        </ul>

        <div class="collapse navbar-collapse">
          <div class="navbar-nav"></div>
        </div>
      </div>
    </nav>
    <div class="container">{% block content %} {% endblock %}</div>
    <div class="container">{% block after_content %}{% endblock %}</div>
  </body>
</html>

movieProject/templates/home.html
{% extends 'base.html' %}

{% block content %}
<div class="jumbotron">
    <h1>Cinema Rate!</h1>
    {% if current_user.is_authenticated %}
    <p>Hi {{current_user.username}}!</p>
    {% else %}
    <p>Please login or register</p>
    {% endif %}
    <img class="container mx-auto" src="https://tinyurl.com/yp99naha" alt="project tracker">
</div>
{% endblock %}